name: setup-pnpm-test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup-pnpm
      - name: Verify node_modules
        run: test -d node_modules
      - name: Verify node version
        run: node -v | grep $(cat .node-version)
